package ProgramasSemana11.EjemplosAWT;

import java.awt.*;

public class Ejemplo3CheckBoxGroup extends java.applet.Applet {
    
    Checkbox chkMusica, chkDeporte, chkAventura;
    TextArea txtS;
    
    CheckboxGroup bgrHobby;

    @Override
    public void init() {
        setLayout(null);
        
        bgrHobby = new CheckboxGroup();
        
        chkMusica = new Checkbox("Musica", bgrHobby, false);
        chkMusica.setBackground(Color.red);
        chkMusica.setForeground(Color.BLUE);
        chkMusica.setBounds(10, 10, 100, 25);
        add(chkMusica);
        
        chkDeporte = new Checkbox("Deporte", bgrHobby, false);
        chkDeporte.setBackground(Color.ORANGE);
        chkDeporte.setBounds(10, 45, 100, 25);
        add(chkDeporte);
        
        chkAventura = new Checkbox("Aventura", bgrHobby, false);
        chkAventura.setBackground(Color.LIGHT_GRAY);
        chkAventura.setBounds(10, 80, 100, 25);
        add(chkAventura);
        
        txtS = new TextArea();
        txtS.setBounds(120, 10, 300, 150);
        add(txtS);   
    }
    
    @Override
    public boolean action(Event e, Object o)
    {
        String eleccion = "Ud. eligió: ";
        if(chkMusica.getState() == true)
            eleccion += "\nMusica";
        if(chkDeporte.getState() == true)
            eleccion += "\nDeporte";
        if(chkAventura.getState() == true)
            eleccion += "\nAventura";
        
        txtS.setText(eleccion);
        return true;
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
